[package]
name = "chipi-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "The `isa!` procedural macro: generate a chipi decoder at compile time."

[lib]
proc-macro = true

[dependencies]
chipi-core.workspace = true
chipi-backend-rust.workspace = true

[lints]
workspace = true
