[package]
name = "chipi-backend-rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Rust source emission backend for chipi."

[dependencies]
chipi-syntax.workspace = true
chipi-core.workspace = true

[lints]
workspace = true
