//! Python 3 decoder emission from a resolved [`chipi_core::Isa`].
//!
//! [`emit_python`] produces one self-contained, dependency-free Python module: opcode names, a dense
//! classification path, shift/mask field accessors, computed-operand accessors, user `fn`s, an
//! optional embedded `length` and a disassembler. It is the IDA / Binary Ninja sibling of
//! the Rust and C++ backends and aims to match the `chipi_core::interp` oracle.
//!
//! The emitter keeps three numeric domains separate, matching the oracle. Field accessors
//! work in 64bit (with a 32/64bit return truncation). The computation layer (computed operands,
//! guards, `length`, `assemble`, builtins, fn bodies) works in unsigned 128bit. Display
//! conditions work in signed 128bit.

#![forbid(unsafe_code)]

mod exprgen;
mod names;

use chipi_core::accessor::computed_accessor_names;
use chipi_core::model::*;
use chipi_core::render::{FmtSpec, Seg};
use chipi_core::tree::{Residual, Tree};
use chipi_core::Isa;
use exprgen::{emit_cond, emit_value, width_mask, Scope};
use names::{cname, comp_acc, pascal, sanitize};

/// Re-exported so tests and tooling can reconstruct the exact handler-method names the `Ops`
/// dispatch layer emits (keyword-sanitised, e.g. `and` -> `and_`).
pub use names::ident;
use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

/// A reason string if the spec uses a feature the Python backend cannot emit yet, else `None`.
fn py_unsupported(isa: &Isa) -> Option<&'static str> {
    let has_fetch = isa.instrs.iter().any(|i| {
        i.computed
            .iter()
            .any(|c| chipi_core::interp::fetch_width(&c.expr).is_some())
    });
    has_fetch.then_some("fetch(N) stream-relative operands")
}

/// Emit a self-contained Python 3 decoder for `isa`.
pub fn emit_python(isa: &Isa) -> String {
    // No stream/context decode here, so `fetch(N)` operands (which live past the opcode window)
    // cannot be read. Refuse loudly on import rather than emit a call to an undefined helper; the
    // Rust backend's contextual disassembler handles such specs.
    if let Some(reason) = py_unsupported(isa) {
        return format!(
            "{}raise NotImplementedError(\"chipi: the Python backend does not support {reason}\")\n",
            header(isa)
        );
    }

    let modal = !isa.modes.is_empty();

    let mut s = String::new();

    s.push_str(&header(isa));
    s.push_str(&imports(isa));
    s.push_str(&opcode_names(isa));
    s.push_str(&preamble(isa));

    s.push_str(&classify(isa, modal));
    s.push_str(&opcode_name_wrapper(modal));

    s.push_str(&field_accessors(isa));
    s.push_str(&user_fns(isa));
    s.push_str(&computed_accessors(isa));
    s.push_str(&length_emit(isa));
    s.push_str(&ops_dispatch(isa, modal));
    s.push_str(&sub_fns_py(isa));
    s.push_str(&disasm_emit(isa, modal));

    s
}

/// Standard-library imports the emitted module needs: `abc` for the `Ops` base class and `enum`
/// only when there are `dispatch` groups (which emit `IntEnum` kind types).
fn imports(isa: &Isa) -> String {
    let mut s = String::from("import abc\n");
    if !isa.groups.is_empty() {
        s.push_str("import enum\n");
    }
    s.push('\n');
    s
}

// ---------------------------------------------------------------- helpers

/// Whether any instruction declares a computed operand.
fn has_computed(isa: &Isa) -> bool {
    isa.instrs.iter().any(|i| !i.computed.is_empty())
}

/// Reverse map from instruction index to opcode id (table slot), 0 if it has none.
fn opcode_ids(isa: &Isa) -> Vec<usize> {
    let mut ids = vec![0usize; isa.instrs.len()];
    for (id, op) in isa.tree.opcodes.iter().enumerate() {
        if op.instr != usize::MAX {
            ids[op.instr] = id;
        }
    }
    ids
}

/// A 64bit-capped width mask literal as Python source.
fn mask64(w: u16) -> String {
    format!("{:#x}", chipi_core::compute::mask_u64(w))
}

/// Debug-format a string as a Python string literal (`{:?}` matches Python's escape conventions).
fn pystr(s: &str) -> String {
    format!("{s:?}")
}

// ---------------------------------------------------------------- sections

fn header(isa: &Isa) -> String {
    format!(
        "# generated by chipi (Python backend) for decoder `{}`. DO NOT EDIT.\n\
         # Output is reproducible; regenerate with `chipi emit`.\n\n",
        isa.decoder.name
    )
}

fn opcode_names(isa: &Isa) -> String {
    let mut s = String::from("OPCODE_NAMES = [\n");

    for op in &isa.tree.opcodes {
        let _ = writeln!(s, "    {},", pystr(&op.name));
    }

    s.push_str("]\n\n");
    s
}

const RUNTIME_PREAMBLE: &str = r#"# ---- runtime preamble ----
_M64 = (1 << 64) - 1

def _mask64(w):
    return _M64 if w >= 64 else (1 << w) - 1

def _sext64(v, n):
    v &= _M64
    if n == 0 or n >= 64:
        return v - (1 << 64) if v & (1 << 63) else v
    v &= _mask64(n)
    return v - (1 << n) if v & (1 << (n - 1)) else v

def _rotl64(v, k, w):
    if w == 0:
        return 0
    m = _mask64(w)
    v &= m
    k %= w
    return v if k == 0 else ((v << k) | (v >> (w - k))) & m

def _rotr64(v, k, w):
    if w == 0:
        return 0
    return _rotl64(v, (w - (k % w)) % w, w)

# ---- disasm display-condition helpers (i128 wrapping semantics) ----
_M128 = (1 << 128) - 1

def _s128(v):
    v &= _M128
    return v - (1 << 128) if v & (1 << 127) else v

def _cshr128(a, b):
    return _s128(a >> b)

def _cdiv128(a, b):
    if b == 0:
        return 0
    q = abs(a) // abs(b)
    return _s128(-q if (a < 0) != (b < 0) else q)

def _crem128(a, b):
    if b == 0:
        return 0
    r = abs(a) % abs(b)
    return _s128(-r if a < 0 else r)

"#;

const COMPUTE_PREAMBLE: &str = r#"# ---- computation-layer preamble (computed operands) ----
def _cmask128(w):
    return _M128 if w >= 128 else (1 << w) - 1

def _sext128(v, n):
    v &= _M128
    if n == 0 or n >= 128:
        return v
    m = _cmask128(n)
    x = v & m
    return (x | (_M128 & ~m)) if (x >> (n - 1)) & 1 else x

def _rotl128(v, n, w, left):
    if w == 0:
        return 0
    m = _cmask128(w)
    v &= m
    n %= w
    if n == 0:
        return v
    (l, r) = (n, w - n) if left else (w - n, n)
    return ((v << l) | (v >> r)) & m

def _bitwidth128(v):
    v &= _M128
    return v.bit_length()

def _replicate128(v, elem, total):
    if elem == 0 or total == 0:
        return 0
    chunk = v & _cmask128(elem)
    out = 0
    sh = 0
    while sh < total:
        out |= chunk << sh
        sh += elem
    return out & _cmask128(total)

def _maskrange128(b, e, w):
    out = 0
    if b <= e:
        i = b
        while i <= e and i < w:
            out |= 1 << i
            i += 1
    else:
        i = b
        while i < w:
            out |= 1 << i
            i += 1
        j = 0
        while j <= e:
            out |= 1 << j
            j += 1
    return out & _cmask128(w)

def _popcount128(v):
    return bin(v & _M128).count('1')

def _ctz128(v, w):
    v &= _M128
    return w if v == 0 else (v & -v).bit_length() - 1

def _div128(a, b):
    return 0 if b == 0 else ((a // b) & _M128)

def _rem128(a, b):
    return 0 if b == 0 else ((a % b) & _M128)

"#;

fn preamble(isa: &Isa) -> String {
    let mut s = String::from(RUNTIME_PREAMBLE);

    if has_computed(isa) || !isa.fns.is_empty() || isa.length.is_some() {
        s.push_str(COMPUTE_PREAMBLE);
    }

    s
}

/// A dense primary table as a Python list literal.
fn primary_table(tree: &Tree, suffix: &str) -> String {
    let base = tree.opcode_count();

    let mut row = String::new();
    for slot in &tree.slots {
        let v = slot.table_value(base);
        let _ = write!(row, "{v},");
    }

    format!("_PRIMARY{suffix} = [{row}]\n\n")
}

/// The body of a routing function (statements with 4-space indent, no `def` line).
fn routing_body(tree: &Tree, table: &str) -> String {
    let base = tree.opcode_count();
    let p_lo = tree.primary.range.lo;
    let p_mask = mask64(tree.primary.range.width());

    let mut s = String::new();
    let _ = writeln!(s, "    primary = (word >> {p_lo}) & {p_mask}");

    if tree.residuals.is_empty() {
        let _ = writeln!(s, "    return {table}[primary]");
        return s;
    }

    let _ = writeln!(s, "    slot = {table}[primary]");

    for (ri, r) in tree.residuals.iter().enumerate() {
        let sentinel = base + ri;
        let _ = writeln!(s, "    if slot == {sentinel}:");

        match r {
            Residual::Keyed {
                key, arms, default, ..
            } => {
                let k_lo = key.range.lo;
                let k_mask = mask64(key.range.width());

                let _ = writeln!(s, "        k = (word >> {k_lo}) & {k_mask}");
                for (kv, id) in arms {
                    let _ = writeln!(s, "        if k == {kv:#x}: return {id}");
                }
                let _ = writeln!(s, "        return {default}");
            }
            Residual::Sparse { arms, .. } => {
                for a in arms {
                    let _ = writeln!(
                        s,
                        "        if (word & {:#x}) == {:#x}: return {}",
                        a.mask, a.val, a.opcode
                    );
                }
                s.push_str("        return 0\n");
            }
        }
    }

    s.push_str("    return slot\n");
    s
}

fn classify(isa: &Isa, modal: bool) -> String {
    let mut s = String::new();

    if modal {
        for (i, tree) in isa.mode_trees.iter().enumerate() {
            s.push_str(&primary_table(tree, &format!("_{i}")));
            let _ = writeln!(s, "def _classify_{i}(word):");
            s.push_str(&routing_body(tree, &format!("_PRIMARY_{i}")));
            s.push('\n');
        }

        let _ = writeln!(s, "MODE_COMBOS = {}\n", isa.mode_combos());

        s.push_str("def classify(combo, word):\n");
        for i in 0..isa.mode_trees.len() {
            let _ = writeln!(s, "    if combo == {i}: return _classify_{i}(word)");
        }
        s.push_str("    return 0\n\n");

        let params: Vec<String> = isa.modes.iter().map(|m| sanitize(&m.name)).collect();
        let _ = writeln!(s, "def pack_modes({}):", params.join(", "));
        s.push_str("    idx = 0\n    radix = 1\n");
        for m in &isa.modes {
            let _ = writeln!(
                s,
                "    idx += ({} % {c}) * radix; radix *= {c}",
                sanitize(&m.name),
                c = m.cardinality
            );
        }
        s.push_str("    return idx\n\n");

        return s;
    }

    s.push_str(&primary_table(&isa.tree, ""));

    let has_guard = isa.instrs.iter().any(|i| i.guard.is_some());
    if has_guard {
        s.push_str("def _classify_raw(word):\n");
        s.push_str(&routing_body(&isa.tree, "_PRIMARY"));
        s.push('\n');

        s.push_str("def classify(word):\n");
        s.push_str("    __id = _classify_raw(word)\n");

        let ids = opcode_ids(isa);
        for &idx in &isa.instr_order() {
            let inst = &isa.instrs[idx];
            if let Some(g) = &inst.guard {
                let id = ids[idx];
                let scope = Scope::Computed {
                    fields: &inst.fields,
                    window: isa.window_bits(),
                    base: "word",
                };
                let _ = writeln!(
                    s,
                    "    if __id == {id} and not (({}) != 0): return 0",
                    emit_value(g, &scope)
                );
            }
        }

        s.push_str("    return __id\n\n");
    } else {
        s.push_str("def classify(word):\n");
        s.push_str(&routing_body(&isa.tree, "_PRIMARY"));
        s.push('\n');
    }

    s
}

fn opcode_name_wrapper(modal: bool) -> String {
    if modal {
        "def opcode_name_in(combo, word):\n    return OPCODE_NAMES[classify(combo, word)]\n\n"
            .to_string()
    } else {
        "def opcode_name(word):\n    return OPCODE_NAMES[classify(word)]\n\n".to_string()
    }
}

fn field_accessors(isa: &Isa) -> String {
    let mut s = String::new();

    for (name, f) in isa.unique_fields() {
        let _ = writeln!(s, "def {}(word):", ident(&name));
        let _ = writeln!(
            s,
            "    v = (word >> {}) & {}",
            f.range.lo,
            mask64(f.range.width())
        );

        let mut signed = false;
        for x in &f.ty.xforms {
            match x {
                Xform::ShiftLeft(n) => {
                    if signed {
                        let _ = writeln!(s, "    v = _sext64((v << {n}) & _M64, 64)");
                    } else {
                        let _ = writeln!(s, "    v = (v << {n}) & _M64");
                    }
                }
                Xform::ShiftRight(n) => {
                    let _ = writeln!(s, "    v = v >> {n}");
                }
                Xform::ZeroExtend(n) => {
                    let _ = writeln!(s, "    v &= {}", mask64(*n));
                    signed = false;
                }
                Xform::SignExtend(n) => {
                    let _ = writeln!(s, "    v = _sext64(v & _M64, {n})");
                    signed = true;
                }
                Xform::RotateLeft(k, w) => {
                    let _ = writeln!(s, "    v = _rotl64(v & _M64, {k}, {w})");
                    signed = false;
                }
                Xform::RotateRight(k, w) => {
                    let _ = writeln!(s, "    v = _rotr64(v & _M64, {k}, {w})");
                    signed = false;
                }
            }
        }
        // return-type truncation
        let bits = if f.ty.value_width <= 32 { 32u32 } else { 64 };
        let m = if bits >= 64 {
            u64::MAX
        } else {
            (1u64 << bits) - 1
        };
        let _ = writeln!(s, "    v &= {m:#x}");

        if f.ty.signed {
            let sign = 1u128 << (bits - 1);
            let span = 1u128 << bits;
            let _ = writeln!(s, "    if v & {sign:#x}: v -= {span:#x}");
        }

        s.push_str("    return v\n\n");
    }

    s
}

fn user_fns(isa: &Isa) -> String {
    if isa.fns.is_empty() {
        return String::new();
    }

    let mut s = String::from("# ---- user fns (computation layer) ----\n");

    for f in &isa.fns {
        let params: Vec<String> = f
            .params
            .iter()
            .map(|(n, _)| format!("v_{}", sanitize(n)))
            .collect();
        let _ = writeln!(s, "def fn_{}({}):", sanitize(&f.name), params.join(", "));

        let mut widths: HashMap<String, u16> = f
            .params
            .iter()
            .map(|(n, ty)| (n.clone(), ty.width()))
            .collect();
        for (n, ty) in &f.params {
            let _ = writeln!(
                s,
                "    v_{} = v_{} & _cmask128({})",
                sanitize(n),
                sanitize(n),
                ty.width()
            );
        }

        for (ln, le) in &f.lets {
            let scope = Scope::Fn {
                widths: widths.clone(),
            };
            let _ = writeln!(s, "    v_{} = {}", sanitize(ln), emit_value(le, &scope));

            let w = chipi_core::compute::infer_width(
                le,
                &chipi_core::compute::WidthEnv {
                    word_width: 64,
                    field_width: &|n: &str| widths.get(n).copied(),
                },
            );
            widths.insert(ln.clone(), w);
        }

        let scope = Scope::Fn { widths };
        let _ = writeln!(
            s,
            "    return ({}) & _cmask128({})",
            emit_value(&f.ret_expr, &scope),
            f.ret.width()
        );

        s.push('\n');
    }

    s
}

fn computed_accessors(isa: &Isa) -> String {
    if !has_computed(isa) {
        return String::new();
    }

    let acc = computed_accessor_names(isa);
    let mut emitted: HashSet<String> = HashSet::new();
    let mut s = String::new();

    for &idx in &isa.instr_order() {
        let inst = &isa.instrs[idx];
        for c in &inst.computed {
            // Folded operands share one accessor; emit each unique name once.
            let method = comp_acc(&acc, &inst.name, &c.name);
            if !emitted.insert(method.clone()) {
                continue;
            }

            let scope = Scope::Computed {
                fields: &inst.fields,
                window: isa.window_bits(),
                base: "word",
            };

            let _ = writeln!(s, "def {method}(word):");
            let _ = writeln!(s, "    __v = ({}) & _M128", emit_value(&c.expr, &scope));

            if c.ty.signed {
                let _ = writeln!(s, "    __v = _sext128(__v, {})", c.ty.value_width);
                s.push_str("    return __v - (1 << 128) if __v & (1 << 127) else __v\n");
            } else {
                let _ = writeln!(s, "    return __v & _cmask128({})", c.ty.value_width);
            }

            s.push('\n');
        }
    }

    s
}

fn length_emit(isa: &Isa) -> String {
    let mut s = String::new();
    match &isa.length {
        None => {
            let _ = writeln!(s, "LEN = {}\n", isa.max_len_bytes);
            s.push_str("def inst_len(word):\n    return LEN\n\n");
        }
        Some(len) => {
            s.push_str("def inst_len_bits(word):\n");

            for arm in &len.arms {
                match &arm.cond {
                    Some(c) => {
                        // length conditions use the computation layer and reference only `word`.
                        let scope = Scope::Computed {
                            fields: &[],
                            window: isa.window_bits(),
                            base: "word",
                        };
                        let _ = writeln!(
                            s,
                            "    if ({}) != 0: return {}",
                            emit_value(c, &scope),
                            arm.bits
                        );
                    }
                    None => {
                        let _ = writeln!(s, "    return {}", arm.bits);
                    }
                }
            }

            s.push_str("    return 0\n\n");
            s.push_str("def inst_len(word):\n    return (inst_len_bits(word) + 7) // 8\n\n");
        }
    }
    s
}

// ---------------------------------------------------------------- dispatch (Ops)

/// Maps each member name to its group name, for every instruction folded into a `dispatch` group.
fn grouped_members(isa: &Isa) -> HashMap<String, String> {
    let mut grouped = HashMap::new();
    for g in &isa.groups {
        for member in &g.members {
            grouped.insert(member.clone(), g.name.clone());
        }
    }
    grouped
}

/// The operand-signature `Ops` dispatch layer, mirroring the Rust and C++ backends: module-level
/// `OP_*` opcode-id constants, an `IntEnum` kind per `dispatch` group, an `Ops` base class whose
/// handlers receive the decoded word and `dispatch_ops`/`run_ops`. Each group folds its members
/// behind one handler (defaulting to the per-member handlers); every ungrouped instruction is an
/// `abc.abstractmethod` the consumer must implement.
fn ops_dispatch(isa: &Isa, modal: bool) -> String {
    let grouped = grouped_members(isa);

    let mut s = String::new();
    s.push_str("# ---- context-generic dispatch (Ops) ----\n");

    for (id, op) in isa.tree.opcodes.iter().enumerate() {
        let _ = writeln!(s, "OP_{} = {id}", cname(&op.name));
    }
    s.push('\n');

    for g in &isa.groups {
        let _ = writeln!(s, "class {}Kind(enum.IntEnum):", pascal(&g.name));
        for (i, member) in g.members.iter().enumerate() {
            let _ = writeln!(s, "    {} = {i}", cname(member));
        }
        s.push('\n');
    }

    s.push_str("class Ops(abc.ABC):\n");
    s.push_str(
        "    \"\"\"Implement once per consumer; pull operands via the accessors above.\"\"\"\n\n",
    );

    for g in &isa.groups {
        let kind = format!("{}Kind", pascal(&g.name));
        let _ = writeln!(s, "    def {}(self, op, inst):", ident(&g.name));
        for (i, member) in g.members.iter().enumerate() {
            let kw = if i == 0 { "if" } else { "elif" };
            let _ = writeln!(s, "        {kw} op == {kind}.{}:", cname(member));
            let _ = writeln!(s, "            self.{}(inst)", ident(member));
        }
        s.push('\n');
        for member in &g.members {
            let _ = writeln!(s, "    def {}(self, inst):", ident(member));
            s.push_str("        pass\n\n");
        }
    }

    for &idx in &isa.instr_order() {
        let inst = &isa.instrs[idx];
        if grouped.contains_key(&inst.name) {
            continue;
        }
        s.push_str("    @abc.abstractmethod\n");
        let _ = writeln!(s, "    def {}(self, inst):", ident(&inst.name));
        s.push_str("        ...\n\n");
    }

    s.push_str("    def on_invalid(self, inst):\n        pass\n\n\n");

    let (sig, classify_args) = if modal {
        ("combo, h, inst", "combo, inst")
    } else {
        ("h, inst", "inst")
    };
    let _ = writeln!(s, "def dispatch_ops({sig}):");
    let _ = writeln!(s, "    op = classify({classify_args})");
    let mut first = true;
    for &idx in &isa.instr_order() {
        let inst = &isa.instrs[idx];
        let kw = if first { "if" } else { "elif" };
        first = false;
        if let Some(group) = grouped.get(&inst.name) {
            let _ = writeln!(s, "    {kw} op == OP_{}:", cname(&inst.name));
            let _ = writeln!(
                s,
                "        h.{}({}Kind.{}, inst)",
                ident(group),
                pascal(group),
                cname(&inst.name)
            );
        } else {
            let _ = writeln!(s, "    {kw} op == OP_{}:", cname(&inst.name));
            let _ = writeln!(s, "        h.{}(inst)", ident(&inst.name));
        }
    }
    s.push_str("    else:\n        h.on_invalid(inst)\n\n\n");

    let (run_sig, dispatch_args) = if modal {
        ("combo, h, word", "combo, h, word")
    } else {
        ("h, word", "h, word")
    };
    let _ = writeln!(s, "def run_ops({run_sig}):");
    let _ = writeln!(s, "    dispatch_ops({dispatch_args})");
    s.push_str("    return inst_len(word)\n\n");

    s
}

// ---------------------------------------------------------------- disassembly

/// Resolve a `{name}` placeholder: computed operand, else bound field, else fallback.
fn render_field_py(
    accmap: &HashMap<(String, String), String>,
    inst: &Insn,
    name: &str,
    fmt: &FmtSpec,
) -> String {
    if let Some(c) = inst.computed.iter().find(|c| c.name == name) {
        let acc = format!("{}(word)", comp_acc(accmap, &inst.name, name));
        return render_value_py(&c.ty, &acc, fmt);
    }

    if let Some(f) = inst.fields.iter().find(|f| f.name == name) {
        let acc = format!("{}(word)", ident(name));
        return render_value_py(&f.ty, &acc, fmt);
    }

    format!("str({}(word))", ident(name))
}

/// Render one operand value against its type's display spec and a placeholder format.
fn render_value_py(ty: &FieldTy, acc: &str, fmt: &FmtSpec) -> String {
    if fmt.hex {
        return py_hex_str(ty, acc, fmt.alt, fmt.zero_pad);
    }
    if fmt.dec {
        return py_dec_str(ty, acc);
    }

    match &ty.disp {
        Disp::Pattern(p) => {
            // Substitute the value at every `{}`, matching render::render_field's
            // `p.replace("{}", ...)` and the C++ backend.
            let val = py_dec_str(ty, acc);
            let parts: Vec<&str> = p.split("{}").collect();

            let mut pieces: Vec<String> = Vec::new();
            for (i, part) in parts.iter().enumerate() {
                if i > 0 {
                    pieces.push(val.clone());
                }
                if !part.is_empty() {
                    pieces.push(pystr(part));
                }
            }

            if pieces.is_empty() {
                pystr("")
            } else {
                pieces.join(" + ")
            }
        }
        Disp::Hint(DispHint::Hex) => py_hex_str(ty, acc, true, 0),
        Disp::Hint(DispHint::SignedHex) => {
            format!("((\"-0x%x\" % -({acc})) if ({acc}) < 0 else (\"0x%x\" % ({acc})))")
        }
        Disp::Hint(DispHint::Dec) => py_dec_str(ty, acc),
        Disp::Names(t) => {
            let default = match &t.default {
                NameDefault::Str(s) => pystr(s),
                NameDefault::Hint(DispHint::Dec) => py_dec_str(ty, acc),
                NameDefault::Hint(DispHint::Hex) => py_hex_str(ty, acc, true, 0),
                NameDefault::Hint(DispHint::SignedHex) => {
                    format!("((\"-0x%x\" % -({acc})) if ({acc}) < 0 else (\"0x%x\" % ({acc})))")
                }
            };
            let mut dict = String::from("{");
            for (i, (k, name)) in t.entries.iter().enumerate() {
                if i > 0 {
                    dict.push_str(", ");
                }
                dict.push_str(&format!("{k}: {}", pystr(name)));
            }
            dict.push('}');
            format!("({dict}.get(({acc}), {default}))")
        }
        Disp::None => {
            if ty.signed {
                py_dec_str(ty, acc)
            } else {
                py_hex_str(ty, acc, true, 0)
            }
        }
    }
}

fn py_dec_str(ty: &FieldTy, acc: &str) -> String {
    if ty.signed {
        format!("str({acc})")
    } else {
        format!("str(({acc}) & {})", width_mask(ty.value_width))
    }
}

fn py_hex_str(ty: &FieldTy, acc: &str, alt: bool, zero_pad: usize) -> String {
    let mag = if ty.signed {
        format!(
            "((({acc}) & {}) if ({acc}) < 0 else ({acc}))",
            width_mask(ty.value_width.max(1))
        )
    } else {
        format!("(({acc}) & {})", width_mask(ty.value_width))
    };

    let inner = if zero_pad > 0 {
        format!("(\"%0{zero_pad}x\" % {mag})")
    } else {
        format!("(\"%x\" % {mag})")
    };

    if alt {
        format!("(\"0x\" + {inner})")
    } else {
        inner
    }
}

/// A Python string-concatenation expression for a list of segments (always begins with `""`).
fn arm_string_expr(
    accmap: &HashMap<(String, String), String>,
    inst: &Insn,
    segs: &[Seg],
) -> String {
    let mut s = String::from("\"\"");

    for seg in segs {
        match seg {
            Seg::Lit(t) => {
                let _ = write!(s, " + {}", pystr(t));
            }
            Seg::Field { name, fmt } => {
                let _ = write!(s, " + {}", render_field_py(accmap, inst, name, fmt));
            }
            Seg::Cond { cond, then, els } => {
                let _ = write!(
                    s,
                    " + (({}) if ({}) != 0 else ({}))",
                    arm_string_expr(accmap, inst, then),
                    emit_cond(cond, inst, accmap),
                    arm_string_expr(accmap, inst, els)
                );
            }
            Seg::SubField { field, output } => {
                if let Some(f) = inst.fields.iter().find(|f| &f.name == field) {
                    if let Some(sdn) = &f.ty.subdecoder {
                        let _ = write!(
                            s,
                            " + {}({}(word))",
                            sub_fn_name_py(sdn, output),
                            ident(field)
                        );
                    }
                }
            }
        }
    }

    s
}

/// The emitted sub-render function name for a `(subdecoder, output)` pair.
fn sub_fn_name_py(subdecoder: &str, output: &str) -> String {
    format!("sub_{}_{}", sanitize(subdecoder), sanitize(output))
}

/// Emit one `def sub_<name>_<output>(v)` per subdecoder output: an ordered chain of
/// `if (v & mask) == val: return <template>` arms (most-specific-first).
fn sub_fns_py(isa: &Isa) -> String {
    let mut s = String::new();
    for sd in &isa.subdecoders {
        for oname in &sd.outputs {
            let _ = writeln!(s, "def {}(v):", sub_fn_name_py(&sd.name, oname));
            for arm in &sd.arms {
                let segs = arm.output(oname).unwrap_or(&[]);
                let _ = writeln!(
                    s,
                    "    if (v & {:#x}) == {:#x}: return {}",
                    arm.mask,
                    arm.val,
                    sub_segs_py(segs, &arm.fields)
                );
            }
            s.push_str("    return \"\"\n\n");
        }
    }
    s
}

fn sub_segs_py(segs: &[Seg], fields: &[Field]) -> String {
    let mut parts: Vec<String> = vec!["\"\"".to_string()];
    for seg in segs {
        match seg {
            Seg::Lit(t) => parts.push(pystr(t)),
            Seg::Field { name, fmt } => {
                if let Some(f) = fields.iter().find(|f| &f.name == name) {
                    let valexpr = format!("((v >> {}) & {})", f.range.lo, mask64(f.range.width()));
                    parts.push(render_value_py(&f.ty, &valexpr, fmt));
                }
            }
            // Conditionals and nested sub-fields are rejected in subdecoder outputs at resolution.
            Seg::Cond { .. } | Seg::SubField { .. } => {}
        }
    }
    parts.join(" + ")
}

fn disasm_emit(isa: &Isa, modal: bool) -> String {
    let accmap = computed_accessor_names(isa);
    let mut s = String::new();

    if modal {
        s.push_str("def disasm(combo, word):\n    op = classify(combo, word)\n");
    } else {
        s.push_str("def disasm(word):\n    op = classify(word)\n");
    }

    let ids = opcode_ids(isa);
    let mut first = true;
    for &idx in &isa.instr_order() {
        let inst = &isa.instrs[idx];
        let id = ids[idx];

        let kw = if first { "if" } else { "elif" };
        first = false;

        let _ = writeln!(s, "    {kw} op == {id}:");
        s.push_str(&disasm_arms(&accmap, inst));
    }

    s.push_str("    return \"(invalid)\"\n");
    s
}

/// The display-arm chain for one instruction (8-space indented statements under the `op ==` branch).
fn disasm_arms(accmap: &HashMap<(String, String), String>, inst: &Insn) -> String {
    let mut s = String::new();

    let mut first = true;
    let mut had_uncond = false;
    for arm in &inst.display {
        match &arm.cond {
            Some(c) => {
                let kw = if first { "if" } else { "elif" };
                let _ = writeln!(s, "        {kw} ({}) != 0:", emit_cond(c, inst, accmap));
                let _ = writeln!(
                    s,
                    "            return {}",
                    arm_string_expr(accmap, inst, &arm.segs)
                );
                first = false;
            }
            None => {
                if first {
                    let _ = writeln!(
                        s,
                        "        return {}",
                        arm_string_expr(accmap, inst, &arm.segs)
                    );
                } else {
                    s.push_str("        else:\n");
                    let _ = writeln!(
                        s,
                        "            return {}",
                        arm_string_expr(accmap, inst, &arm.segs)
                    );
                }
                had_uncond = true;
                break;
            }
        }
    }

    if !had_uncond {
        let _ = writeln!(s, "        return {}", pystr(&inst.name));
    }

    s
}
