//! C++17 source emission backend for chipi.
//!
//! [`emit_cpp`] produces one self-contained C++17 header (`#pragma once`, `namespace chipi`).
//! It decodes and disassembles the same as the [`chipi_core`] oracle and emits the same
//! operand-signature `Ops` dispatch layer as the Rust backend (an abstract `Ops` base class plus
//! `dispatch_ops`/`run_ops`). It depends only on `<cstdint>`, `<cstdio>`, `<string>` and GCC/Clang's
//! native `unsigned __int128` / `__int128`.

#![forbid(unsafe_code)]

mod exprgen;
mod names;

use chipi_core::accessor::computed_accessor_names;
use chipi_core::model::*;
use chipi_core::render::{FmtSpec, Seg};
use chipi_core::tree::{Residual, Tree};
use chipi_core::Isa;
use exprgen::{emit_cond, emit_value, Scope};
use names::{c_string, cname, computed_method, mask_u64, pascal, ret_type, sanitize};

/// Re-exported so tests and tooling can reconstruct the exact handler-method names the `Ops`
/// dispatch layer emits (keyword-sanitised, e.g. `and` -> `and_`).
pub use names::ident;
use std::collections::{BTreeMap, HashMap, HashSet};

/// The deduplicated accessor function name for one instruction's computed operand.
fn comp_acc(acc: &HashMap<(String, String), String>, inst: &Insn, c: &Computed) -> String {
    computed_method(&acc[&(inst.name.clone(), c.name.clone())])
}
use std::fmt::Write as _;

/// Emit a self-contained C++17 decoder for `isa`.
pub fn emit_cpp(isa: &Isa) -> String {
    // The C++ backend has no stream/context decode, so it cannot read `fetch(N)` operands (which
    // live past the opcode window). Refuse such a spec loudly with a `#error` rather than emit a
    // call to a function that does not exist. The Rust backend's contextual disassembler handles it.
    if let Some(reason) = cpp_unsupported(isa) {
        return format!(
            "{}#error \"chipi: the C++ backend does not support {reason}\"\n",
            header(isa)
        );
    }

    let m = Model::new(isa);
    let mut s = String::new();
    s.push_str(&header(isa));
    s.push_str("#pragma once\n#include <cstdint>\n#include <cstdio>\n#include <string>\n\n");
    s.push_str("namespace chipi {\n");
    s.push_str(&preamble(&m));
    s.push_str(&opcode_consts(isa));
    s.push_str(&user_fns(isa));
    s.push_str(&classify(isa, &m));
    s.push_str(&field_accessors(isa));
    s.push_str(&computed_accessors(isa, &m));
    s.push_str(&length_and_decode(isa));
    s.push_str(&ops_dispatch(isa, &m));
    s.push_str(&sub_fns_cpp(isa));
    s.push_str(&disasm_fn(isa, &m));
    s.push_str("} // namespace chipi\n");
    s
}

/// A reason string if the spec uses a feature the C++ backend cannot emit yet, else `None`.
fn cpp_unsupported(isa: &Isa) -> Option<&'static str> {
    let has_fetch = isa.instrs.iter().any(|i| {
        i.computed
            .iter()
            .any(|c| chipi_core::interp::fetch_width(&c.expr).is_some())
    });
    has_fetch.then_some("fetch(N) stream-relative operands")
}

/// Flags derived once.
struct Model {
    modal: bool,
    has_guard: bool,
    has_computed: bool,
    needs_preamble128: bool,
}

impl Model {
    fn new(isa: &Isa) -> Self {
        let modal = !isa.modes.is_empty();
        let has_guard = isa.instrs.iter().any(|i| i.guard.is_some());
        let has_computed = isa.instrs.iter().any(|i| !i.computed.is_empty());
        let needs_preamble128 =
            has_computed || !isa.fns.is_empty() || isa.length.is_some() || has_guard;
        Model {
            modal,
            has_guard,
            has_computed,
            needs_preamble128,
        }
    }
}

/// Opcode-id constant for a tree id (id 0 is always `OP_INVALID`).
fn id_const(tree: &Tree, id: usize) -> String {
    format!("OP_{}", cname(&tree.opcodes[id].name))
}

/// The handle type for `isa`.
fn handle_ty(isa: &Isa) -> &'static str {
    match isa.handle_bits() {
        8 => "uint8_t",
        16 => "uint16_t",
        32 => "uint32_t",
        _ => "uint64_t",
    }
}

// ---------------------------------------------------------------- sections

fn header(isa: &Isa) -> String {
    format!(
        "// generated by chipi (C++ backend) for decoder `{}` ({}bit unit, {:?}, {:?}). DO NOT EDIT.\n",
        isa.decoder.name, isa.decoder.unit_bits, isa.decoder.bit_order, isa.decoder.endian
    )
}

const RUNTIME_PREAMBLE: &str = r#"// ---- runtime preamble ----
static inline int64_t sext64(uint64_t v, unsigned n) {
    if (n == 0 || n >= 64) return (int64_t)v;
    unsigned shift = 64 - n;
    return ((int64_t)(v << shift)) >> shift;
}
static inline uint64_t rotl64(uint64_t v, unsigned k, unsigned w) {
    if (w == 0) return 0;
    uint64_t m = (w >= 64) ? ~(uint64_t)0 : ((uint64_t)1 << w) - 1;
    v &= m; k %= w;
    if (k == 0) return v;
    return ((v << k) | (v >> (w - k))) & m;
}

"#;

const COMPUTE_PREAMBLE: &str = r#"// ---- computation-layer preamble (computed operands) ----
using u128 = unsigned __int128;
static inline u128 cmask128(uint16_t w) { return (w >= 128) ? (u128)(~(u128)0) : (((u128)1 << w) - 1); }
static inline u128 sext128(u128 v, uint16_t n) {
if (n == 0 || n >= 128) return v;
u128 m = cmask128(n);
u128 x = v & m;
if (((x >> (n - 1)) & 1) == 1) return x | ~m; else return x;
}
static inline u128 rotl128(u128 v, u128 n, uint16_t w, bool left) {
if (w == 0) return 0;
u128 m = cmask128(w);
v &= m;
unsigned nn = (unsigned)(n % (u128)w);
if (nn == 0) return v;
unsigned l, r;
if (left) { l = nn; r = (unsigned)w - nn; } else { l = (unsigned)w - nn; r = nn; }
return ((v << l) | (v >> r)) & m;
}
static inline u128 bitwidth128(u128 v) {
uint16_t i = 128;
while (i > 0 && ((v >> (i - 1)) & 1) == 0) i--;
return (u128)i;
}
static inline u128 ctz128(u128 v, uint16_t w) {
if (v == 0) return (u128)w;
uint16_t i = 0;
while (((v >> i) & 1) == 0) i++;
return (u128)i;
}
static inline u128 popcount128(u128 v) {
u128 c = 0;
while (v) { c += (u128)(v & 1); v >>= 1; }
return c;
}
static inline u128 replicate128(u128 v, uint16_t elem, uint16_t total) {
if (elem == 0 || total == 0) return 0;
u128 chunk = v & cmask128(elem);
u128 out = 0; uint16_t sh = 0;
while (sh < total) { out |= chunk << sh; sh += elem; }
return out & cmask128(total);
}
static inline u128 maskrange128(uint16_t b, uint16_t e, uint16_t w) {
u128 out = 0;
if (b <= e) {
uint16_t i = b; while (i <= e && i < w) { out |= (u128)1 << i; i++; }
} else {
uint16_t i = b; while (i < w) { out |= (u128)1 << i; i++; }
uint16_t j = 0; while (j <= e) { out |= (u128)1 << j; j++; }
}
return out & cmask128(w);
}

"#;

fn preamble(m: &Model) -> String {
    let mut s = String::from(RUNTIME_PREAMBLE);
    if m.needs_preamble128 {
        s.push_str(COMPUTE_PREAMBLE);
    }
    s
}

fn opcode_consts(isa: &Isa) -> String {
    let tree = &isa.tree;
    let mut s = String::new();

    let _ = writeln!(
        s,
        "static const int OPCODE_COUNT = {};\n",
        tree.opcode_count()
    );

    s.push_str("enum Opcode {\n");
    for (id, op) in tree.opcodes.iter().enumerate() {
        let _ = writeln!(s, "    OP_{} = {id},", cname(&op.name));
    }
    s.push_str("};\n");

    s.push_str("static const char* OPCODE_NAMES[] = {\n");
    for op in &tree.opcodes {
        let _ = writeln!(s, "    {},", c_string(&op.name));
    }
    s.push_str("};\n\n");

    s
}

fn user_fns(isa: &Isa) -> String {
    if isa.fns.is_empty() {
        return String::new();
    }
    use std::collections::HashMap;
    let mut s = String::from("// ---- user fns (computation layer) ----\n");

    for f in &isa.fns {
        let params: Vec<String> = f
            .params
            .iter()
            .map(|(n, _)| format!("u128 v_{}", sanitize(n)))
            .collect();
        let _ = writeln!(
            s,
            "static inline u128 fn_{}({}) {{",
            sanitize(&f.name),
            params.join(", ")
        );

        let mut widths: HashMap<String, u16> = f
            .params
            .iter()
            .map(|(n, ty)| (n.clone(), ty.width()))
            .collect();
        for (n, ty) in &f.params {
            let _ = writeln!(s, "    v_{} &= cmask128({});", sanitize(n), ty.width());
        }

        for (ln, le) in &f.lets {
            let scope = Scope::Fn {
                widths: widths.clone(),
            };
            let _ = writeln!(
                s,
                "    u128 v_{} = {};",
                sanitize(ln),
                emit_value(le, &scope)
            );
            widths.insert(ln.clone(), 64);
        }

        let scope = Scope::Fn { widths };
        let _ = writeln!(
            s,
            "    return ({}) & cmask128({});",
            emit_value(&f.ret_expr, &scope),
            f.ret.width()
        );

        s.push_str("}\n\n");
    }

    s
}

/// The element type of a primary table holding `opcode_count + residuals` distinct values.
fn elem_ty(values: usize) -> &'static str {
    if values <= u16::MAX as usize {
        "uint16_t"
    } else {
        "uint32_t"
    }
}

fn primary_table(tree: &Tree, suffix: &str) -> String {
    let base = tree.opcode_count();
    let elem = elem_ty(base + tree.residuals.len());

    let mut s = String::new();
    let _ = writeln!(
        s,
        "static const {elem} PRIMARY{suffix}[{}] = {{",
        tree.slots.len()
    );

    let mut row = String::new();
    for (i, slot) in tree.slots.iter().enumerate() {
        let v = slot.table_value(base);
        row.push_str(&format!("{v},"));
        if i % 16 == 15 {
            row.push('\n');
        }
    }
    if !row.ends_with('\n') {
        row.push('\n');
    }

    s.push_str(&row);
    s.push_str("};\n\n");
    s
}

/// The body of a classification routine for one tree (everything inside the `{ }`).
fn routing_body(tree: &Tree, table: &str) -> String {
    let base = tree.opcode_count();
    let p_lo = tree.primary.range.lo;
    let p_mask = mask_u64(tree.primary.range.width());

    let mut s = String::new();
    let _ = writeln!(
        s,
        "    unsigned primary = ((uint64_t)word >> {p_lo}) & {p_mask:#x}u;"
    );
    if tree.residuals.is_empty() {
        let _ = writeln!(s, "    return (int){table}[primary];");
        return s;
    }

    let _ = writeln!(s, "    unsigned slot = {table}[primary];");
    s.push_str("    switch (slot) {\n");
    for (ri, r) in tree.residuals.iter().enumerate() {
        let sentinel = base + ri;
        match r {
            Residual::Keyed {
                key, arms, default, ..
            } => {
                let k_lo = key.range.lo;
                let k_mask = mask_u64(key.range.width());

                let _ = writeln!(
                    s,
                    "    case {sentinel}: switch (((uint64_t)word >> {k_lo}) & {k_mask:#x}u) {{"
                );
                for (kv, id) in arms {
                    let _ = writeln!(s, "        case {kv:#x}: return {};", id_const(tree, *id));
                }
                let _ = writeln!(s, "        default: return {};", id_const(tree, *default));
                s.push_str("    }\n");
            }
            Residual::Sparse { arms, .. } => {
                let _ = writeln!(s, "    case {sentinel}: {{");
                for a in arms {
                    let _ = writeln!(
                        s,
                        "        if (((uint64_t)word & {:#x}u) == {:#x}u) return {};",
                        a.mask,
                        a.val,
                        id_const(tree, a.opcode)
                    );
                }
                s.push_str("        return OP_INVALID;\n    }\n");
            }
        }
    }
    s.push_str("    default: return (int)slot;\n    }\n");
    s
}

fn classify(isa: &Isa, m: &Model) -> String {
    let handle = handle_ty(isa);
    let mut s = String::new();

    if m.modal {
        for (i, tree) in isa.mode_trees.iter().enumerate() {
            s.push_str(&primary_table(tree, &format!("_{i}")));
            let _ = writeln!(s, "static inline int classify_{i}({handle} word) {{");
            s.push_str(&routing_body(tree, &format!("PRIMARY_{i}")));
            s.push_str("}\n\n");
        }

        let _ = writeln!(s, "static const int MODE_COMBOS = {};\n", isa.mode_combos());
        let _ = writeln!(
            s,
            "static inline int classify(unsigned combo, {handle} word) {{"
        );
        s.push_str("    switch (combo) {\n");
        for i in 0..isa.mode_trees.len() {
            let _ = writeln!(s, "    case {i}: return classify_{i}(word);");
        }
        s.push_str("    default: return 0;\n    }\n}\n\n");

        let params: Vec<String> = isa
            .modes
            .iter()
            .map(|md| format!("uint64_t {}", sanitize(&md.name)))
            .collect();
        let _ = writeln!(
            s,
            "static inline unsigned pack_modes({}) {{",
            params.join(", ")
        );
        s.push_str("    uint64_t idx = 0, radix = 1;\n");
        for md in &isa.modes {
            let _ = writeln!(
                s,
                "    idx += ({} % {c}) * radix; radix *= {c};",
                sanitize(&md.name),
                c = md.cardinality
            );
        }
        s.push_str("    return (unsigned)idx;\n}\n\n");

        let _ = writeln!(
            s,
            "static inline const char* opcode_name(unsigned combo, {handle} word) {{ return OPCODE_NAMES[classify(combo, word)]; }}\n"
        );
        return s;
    }

    s.push_str(&primary_table(&isa.tree, ""));

    if m.has_guard {
        let _ = writeln!(s, "static inline int classify_raw({handle} word) {{");
        s.push_str(&routing_body(&isa.tree, "PRIMARY"));
        s.push_str("}\n\n");

        let _ = writeln!(s, "static inline int classify({handle} word) {{");
        s.push_str("    int __id = classify_raw(word);\n    switch (__id) {\n");
        for &idx in &isa.instr_order() {
            let inst = &isa.instrs[idx];
            if let Some(g) = &inst.guard {
                let scope = Scope::Computed {
                    fields: &inst.fields,
                    window: isa.window_bits(),
                    base: "word",
                };
                let _ = writeln!(
                    s,
                    "    case OP_{}: return (({}) != 0) ? __id : OP_INVALID;",
                    cname(&inst.name),
                    emit_value(g, &scope)
                );
            }
        }
        s.push_str("    default: return __id;\n    }\n}\n\n");
    } else {
        let _ = writeln!(s, "static inline int classify({handle} word) {{");
        s.push_str(&routing_body(&isa.tree, "PRIMARY"));
        s.push_str("}\n\n");
    }

    let _ = writeln!(
        s,
        "static inline const char* opcode_name({handle} word) {{ return OPCODE_NAMES[classify(word)]; }}\n"
    );
    s
}

// ---------------------------------------------------------------- accessors

fn accessor_body(f: &Field) -> String {
    let mut s = format!(
        " uint64_t v = ((uint64_t)w >> {}) & {:#x}u;",
        f.range.lo,
        mask_u64(f.range.width())
    );

    // Mirror interp::apply_xforms: a sign_extend switches the running value to a
    // signed interpretation, so a following shift_right is arithmetic. A
    // zero_extend drops back to the unsigned interpretation.
    let mut signed_mode = false;

    for x in &f.ty.xforms {
        match x {
            Xform::ShiftLeft(n) => s.push_str(&format!(" v <<= {n};")),
            Xform::ShiftRight(n) => {
                if signed_mode {
                    s.push_str(&format!(" v = (uint64_t)((int64_t)v >> {n});"));
                } else {
                    s.push_str(&format!(" v >>= {n};"));
                }
            }
            Xform::ZeroExtend(n) => {
                s.push_str(&format!(" v &= {:#x}u;", mask_u64(*n)));
                signed_mode = false;
            }
            Xform::SignExtend(n) => {
                s.push_str(&format!(" v = (uint64_t)sext64(v, {n});"));
                signed_mode = true;
            }
            Xform::RotateLeft(k, w) => s.push_str(&format!(" v = rotl64(v, {k}, {w});")),
            Xform::RotateRight(k, w) => {
                let kk = if *w == 0 {
                    0u32
                } else {
                    (*w as u32 - (*k as u32 % *w as u32)) % *w as u32
                };
                s.push_str(&format!(" v = rotl64(v, {kk}, {w});"));
            }
        }
    }

    let tail = match (f.ty.signed, f.ty.value_width <= 32) {
        (true, true) => " return (int32_t)(uint32_t)v;",
        (true, false) => " return (int64_t)v;",
        (false, true) => " return (uint32_t)v;",
        (false, false) => " return (uint64_t)v;",
    };
    s.push_str(tail);

    s
}

fn field_accessors(isa: &Isa) -> String {
    let handle = handle_ty(isa);
    let mut s = String::new();
    for (name, f) in isa.unique_fields() {
        let _ = writeln!(
            s,
            "// `{name}` = stream bits [{}:{}]",
            f.range.hi, f.range.lo
        );
        let _ = writeln!(
            s,
            "static inline {} {}({handle} w) {{{} }}",
            ret_type(&f.ty),
            ident(&name),
            accessor_body(f)
        );
    }
    s.push('\n');
    s
}

fn computed_accessors(isa: &Isa, m: &Model) -> String {
    if !m.has_computed {
        return String::new();
    }
    let handle = handle_ty(isa);
    let acc = computed_accessor_names(isa);
    let mut emitted: HashSet<String> = HashSet::new();
    let mut s = String::new();

    for &idx in &isa.instr_order() {
        let inst = &isa.instrs[idx];
        for c in &inst.computed {
            // Folded operands share one accessor; emit each unique name once.
            let method = comp_acc(&acc, inst, c);
            if !emitted.insert(method.clone()) {
                continue;
            }

            let scope = Scope::Computed {
                fields: &inst.fields,
                window: isa.window_bits(),
                base: "word",
            };
            let body = emit_value(&c.expr, &scope);
            let ret = ret_type(&c.ty);

            let cast = if c.ty.signed {
                format!(
                    "u128 __v = {body}; return ({ret})sext128(__v, {});",
                    c.ty.value_width
                )
            } else {
                format!(
                    "u128 __v = {body}; return ({ret})(__v & cmask128({}));",
                    c.ty.value_width
                )
            };

            let _ = writeln!(s, "// computed operand `{}` of `{}`", c.name, inst.name);
            let _ = writeln!(
                s,
                "static inline {ret} {method}({handle} word) {{ {cast} }}"
            );
        }
    }

    s.push('\n');
    s
}

fn length_and_decode(isa: &Isa) -> String {
    let handle = handle_ty(isa);
    let mut s = String::new();

    if let Some(len) = &isa.length {
        let _ = writeln!(s, "static inline uint16_t inst_len_bits({handle} word) {{");

        for arm in &len.arms {
            match &arm.cond {
                Some(c) => {
                    let scope = Scope::Computed {
                        fields: &[],
                        window: isa.window_bits(),
                        base: "word",
                    };
                    let _ = writeln!(
                        s,
                        "    if (({}) != 0) return {};",
                        emit_value(c, &scope),
                        arm.bits
                    );
                }
                None => {
                    let _ = writeln!(s, "    return {};", arm.bits);
                }
            }
        }

        // If the final arm is conditional, nothing guarantees a return, so add a fallback.
        let tail_uncond = len.arms.last().is_some_and(|a| a.cond.is_none());
        if !tail_uncond {
            let fallback = len.arms.last().map(|a| a.bits).unwrap_or(0);
            let _ = writeln!(s, "    return {fallback};");
        }
        s.push_str("}\n");

        let _ = writeln!(
            s,
            "static inline uint8_t inst_len({handle} word) {{ return (uint8_t)((inst_len_bits(word) + 7) / 8); }}\n"
        );
    } else {
        let _ = writeln!(s, "static const uint8_t LEN = {};", isa.max_len_bytes);
        let _ = writeln!(
            s,
            "static inline uint8_t inst_len({handle}) {{ return LEN; }}\n"
        );
    }
    s
}

// ---------------------------------------------------------------- dispatch (Ops)

/// Maps each member name to its group name, for every instruction folded into a `dispatch` group.
fn grouped_members(isa: &Isa) -> HashMap<String, String> {
    let mut grouped = HashMap::new();
    for g in &isa.groups {
        for member in &g.members {
            grouped.insert(member.clone(), g.name.clone());
        }
    }
    grouped
}

/// The operand-signature `Ops` dispatch layer: an abstract base class whose handlers receive the
/// decoded `Instruction`, plus `dispatch_ops`/`run_ops`. This mirrors the Rust backend's `Ops`
/// trait. Each `dispatch` group folds its members behind one virtual handler (defaulting to the
/// per-member handlers) and every ungrouped instruction is a pure-virtual handler the consumer
/// must implement.
fn ops_dispatch(isa: &Isa, m: &Model) -> String {
    let handle = handle_ty(isa);
    let grouped = grouped_members(isa);

    let mut s = String::new();
    s.push_str("// ---- context-generic dispatch (Ops) ----\n");
    let _ = writeln!(s, "using Instruction = {handle};\n");

    for g in &isa.groups {
        let variants: Vec<String> = g.members.iter().map(|member| pascal(member)).collect();
        let _ = writeln!(
            s,
            "enum class {}Kind {{ {} }};",
            pascal(&g.name),
            variants.join(", ")
        );
    }
    if !isa.groups.is_empty() {
        s.push('\n');
    }

    s.push_str("// Implement once per consumer; pull operands via the accessors above.\n");
    s.push_str("struct Ops {\n");
    s.push_str("    virtual ~Ops() = default;\n\n");

    for g in &isa.groups {
        let kind = format!("{}Kind", pascal(&g.name));
        let _ = writeln!(
            s,
            "    virtual void {}({kind} op, Instruction inst) {{",
            ident(&g.name)
        );
        s.push_str("        switch (op) {\n");
        for member in &g.members {
            let _ = writeln!(
                s,
                "        case {kind}::{}: {}(inst); break;",
                pascal(member),
                ident(member)
            );
        }
        s.push_str("        }\n    }\n");
        for member in &g.members {
            let _ = writeln!(s, "    virtual void {}(Instruction) {{}}", ident(member));
        }
        s.push('\n');
    }

    for &idx in &isa.instr_order() {
        let inst = &isa.instrs[idx];
        if grouped.contains_key(&inst.name) {
            continue;
        }
        let _ = writeln!(
            s,
            "    virtual void {}(Instruction inst) = 0;",
            ident(&inst.name)
        );
    }

    s.push_str("\n    // Called for unmapped encodings; override to trap or log.\n");
    s.push_str("    virtual void on_invalid(Instruction) {}\n");
    s.push_str("};\n\n");

    let (cp, ca) = if m.modal {
        ("unsigned combo, ", "combo, ")
    } else {
        ("", "")
    };

    let _ = writeln!(
        s,
        "static inline void dispatch_ops({cp}Ops& h, Instruction inst) {{"
    );
    let _ = writeln!(s, "    switch (classify({ca}inst)) {{");
    for &idx in &isa.instr_order() {
        let inst = &isa.instrs[idx];
        if let Some(group) = grouped.get(&inst.name) {
            let _ = writeln!(
                s,
                "    case OP_{}: h.{}({}Kind::{}, inst); break;",
                cname(&inst.name),
                ident(group),
                pascal(group),
                pascal(&inst.name)
            );
        } else {
            let _ = writeln!(
                s,
                "    case OP_{}: h.{}(inst); break;",
                cname(&inst.name),
                ident(&inst.name)
            );
        }
    }
    s.push_str("    default: h.on_invalid(inst); break;\n    }\n}\n\n");

    let _ = writeln!(
        s,
        "static inline uint8_t run_ops({cp}Ops& h, {handle} word) {{"
    );
    let _ = writeln!(s, "    dispatch_ops({ca}h, (Instruction)word);");
    s.push_str("    return inst_len(word);\n}\n\n");

    s
}

// ---------------------------------------------------------------- disasm

/// Maps each operand name to its accessor call and value type, for one instruction (bound fields then computed).
/// Computed operands use their deduplicated accessor name from `acc_names`.
fn op_acc(
    acc_names: &HashMap<(String, String), String>,
    inst: &Insn,
) -> BTreeMap<String, (String, FieldTy)> {
    let mut m = BTreeMap::new();

    for f in &inst.fields {
        m.insert(
            f.name.clone(),
            (format!("{}(word)", ident(&f.name)), f.ty.clone()),
        );
    }

    for c in &inst.computed {
        m.insert(
            c.name.clone(),
            (
                format!("{}(word)", comp_acc(acc_names, inst, c)),
                c.ty.clone(),
            ),
        );
    }
    m
}

fn acc_methods(acc: &BTreeMap<String, (String, FieldTy)>) -> BTreeMap<String, String> {
    acc.iter()
        .map(|(k, (m, _))| (k.clone(), m.clone()))
        .collect()
}

/// The hex magnitude expression for a value of type `ty`.
fn hex_magnitude(acc: &str, ty: &FieldTy) -> String {
    if ty.signed {
        let mask = mask_u64(ty.value_width.min(64));
        format!("((unsigned long long)({acc}) & {mask:#x}ull)")
    } else {
        format!("(unsigned long long)({acc})")
    }
}

fn field_write(name: &str, fmt: &FmtSpec, acc: &BTreeMap<String, (String, FieldTy)>) -> String {
    let Some((method, ty)) = acc.get(name) else {
        return format!(
            "snprintf(buf, sizeof buf, \"%lld\", (long long){}(word)); __r += buf; ",
            ident(name)
        );
    };
    render_call_cpp(method, fmt, ty)
}

/// Render a value expression `call` (an integer-typed C++ expression) of type `ty` under `fmt`,
/// emitting statements that append the rendered text to `__r` (using the local `buf` scratch). Used
/// both by bound-field rendering and by subdecoder output rendering.
fn render_call_cpp(call: &str, fmt: &FmtSpec, ty: &FieldTy) -> String {
    if fmt.hex {
        let inner = if fmt.zero_pad > 0 {
            format!("%0{}llx", fmt.zero_pad)
        } else {
            "%llx".to_string()
        };
        let pfx = if fmt.alt { "0x" } else { "" };
        return format!(
            "snprintf(buf, sizeof buf, \"{pfx}{inner}\", {}); __r += buf; ",
            hex_magnitude(call, ty)
        );
    }

    if fmt.dec {
        return dec_write(call, ty);
    }

    match &ty.disp {
        Disp::Pattern(p) => pattern_write(p, call, ty),
        Disp::Hint(DispHint::Hex) => format!(
            "snprintf(buf, sizeof buf, \"0x%llx\", {}); __r += buf; ",
            hex_magnitude(call, ty)
        ),
        Disp::Hint(DispHint::SignedHex) => {
            if ty.signed {
                format!(
                    "{{ long long __v = (long long)({call}); if (__v < 0) snprintf(buf, sizeof buf, \"-0x%llx\", (unsigned long long)(-__v)); else snprintf(buf, sizeof buf, \"0x%llx\", (unsigned long long)__v); __r += buf; }} "
                )
            } else {
                // An unsigned operand is never negative, so signed_hex is just hex magnitude.
                format!(
                    "snprintf(buf, sizeof buf, \"0x%llx\", {}); __r += buf; ",
                    hex_magnitude(call, ty)
                )
            }
        }
        Disp::Hint(DispHint::Dec) => dec_write(call, ty),
        Disp::Names(t) => {
            let default_stmt = match &t.default {
                NameDefault::Str(d) => format!("{{ __r += {}; }}", c_string(d)),
                NameDefault::Hint(DispHint::Dec) => format!("{{ {} }}", dec_write(call, ty)),
                NameDefault::Hint(DispHint::Hex) | NameDefault::Hint(DispHint::SignedHex) => {
                    format!(
                        "{{ snprintf(buf, sizeof buf, \"0x%llx\", {}); __r += buf; }}",
                        hex_magnitude(call, ty)
                    )
                }
            };
            if t.entries.is_empty() {
                default_stmt
            } else {
                let mut s = format!("{{ unsigned long long __nv = (unsigned long long)({call}); ");
                for (k, name) in &t.entries {
                    s.push_str(&format!(
                        "if (__nv == {k}ull) {{ __r += {}; }} else ",
                        c_string(name)
                    ));
                }
                s.push_str(&default_stmt);
                s.push_str(" } ");
                s
            }
        }
        Disp::None => {
            if ty.signed {
                dec_write(call, ty)
            } else {
                format!(
                    "snprintf(buf, sizeof buf, \"0x%llx\", {}); __r += buf; ",
                    hex_magnitude(call, ty)
                )
            }
        }
    }
}

/// Emit a decimal write that respects the operand's signedness. A signed operand
/// prints with %lld. An unsigned one prints with %llu so a high-bit-set value stays positive.
fn dec_write(call: &str, ty: &FieldTy) -> String {
    if ty.signed {
        format!("snprintf(buf, sizeof buf, \"%lld\", (long long)({call})); __r += buf; ")
    } else {
        format!("snprintf(buf, sizeof buf, \"%llu\", (unsigned long long)({call})); __r += buf; ")
    }
}

fn pattern_write(p: &str, call: &str, ty: &FieldTy) -> String {
    let parts: Vec<&str> = p.split("{}").collect();

    let (conv, cast) = if ty.signed {
        ("%lld", "(long long)")
    } else {
        ("%llu", "(unsigned long long)")
    };

    let mut s = String::from("{ ");
    for (i, part) in parts.iter().enumerate() {
        if !part.is_empty() {
            s.push_str(&format!("__r += {}; ", c_string(part)));
        }
        if i + 1 < parts.len() {
            s.push_str(&format!("snprintf(buf, sizeof buf, \"{conv}\", {cast}("));
            s.push_str(call);
            s.push_str(")); __r += buf; ");
        }
    }
    s.push_str("} ");
    s
}

fn seg_stmts(segs: &[Seg], acc: &BTreeMap<String, (String, FieldTy)>) -> String {
    let cond_acc = acc_methods(acc);

    let mut s = String::new();
    for seg in segs {
        match seg {
            Seg::Lit(t) => s.push_str(&format!("__r += {}; ", c_string(t))),
            Seg::Cond { cond, then, els } => {
                s.push_str(&format!(
                    "if (({}) != 0) {{ {}}} else {{ {}}} ",
                    emit_cond(cond, "word", &cond_acc),
                    seg_stmts(then, acc),
                    seg_stmts(els, acc)
                ));
            }
            Seg::Field { name, fmt } => s.push_str(&field_write(name, fmt, acc)),
            Seg::SubField { field, output } => {
                if let Some((method, ty)) = acc.get(field) {
                    if let Some(sdn) = &ty.subdecoder {
                        s.push_str(&format!(
                            "__r += {}((unsigned long long)({method})); ",
                            sub_fn_name_cpp(sdn, output)
                        ));
                    }
                }
            }
        }
    }
    s
}

/// The emitted sub-render function name for a `(subdecoder, output)` pair.
fn sub_fn_name_cpp(subdecoder: &str, output: &str) -> String {
    format!("sub_{}_{}", sanitize(subdecoder), sanitize(output))
}

/// Emit one `std::string sub_<name>_<output>(unsigned long long v)` per subdecoder output: an
/// ordered chain of `if ((v & mask) == val)` arms (most-specific-first) rendering each arm's
/// output template.
fn sub_fns_cpp(isa: &Isa) -> String {
    let mut s = String::new();
    for sd in &isa.subdecoders {
        for oname in &sd.outputs {
            let _ = writeln!(
                s,
                "static inline std::string {}(unsigned long long v) {{",
                sub_fn_name_cpp(&sd.name, oname)
            );
            s.push_str("    char buf[64]; std::string __r; (void)buf; (void)v;\n");
            for arm in &sd.arms {
                let segs = arm.output(oname).unwrap_or(&[]);
                let _ = write!(
                    s,
                    "    if ((v & {:#x}ull) == {:#x}ull) {{ ",
                    arm.mask, arm.val
                );
                sub_segs_cpp(segs, &arm.fields, &mut s);
                s.push_str("return __r; }\n");
            }
            s.push_str("    return __r;\n}\n");
        }
    }
    s
}

fn sub_segs_cpp(segs: &[Seg], fields: &[Field], s: &mut String) {
    for seg in segs {
        match seg {
            Seg::Lit(t) => {
                let _ = write!(s, "__r += {}; ", c_string(t));
            }
            Seg::Field { name, fmt } => {
                if let Some(f) = fields.iter().find(|f| &f.name == name) {
                    let mask = mask_u64(f.range.width());
                    let valexpr = format!("((v >> {}) & {mask:#x}ull)", f.range.lo);
                    s.push_str(&render_call_cpp(&valexpr, fmt, &f.ty));
                }
            }
            // Conditionals and nested sub-fields are rejected in subdecoder outputs at resolution.
            Seg::Cond { .. } | Seg::SubField { .. } => {}
        }
    }
}

fn arms_block(acc_names: &HashMap<(String, String), String>, inst: &Insn) -> String {
    let acc = op_acc(acc_names, inst);
    let cond_acc = acc_methods(&acc);

    let mut code = String::new();
    let mut saw_uncond = false;
    for (i, arm) in inst.display.iter().enumerate() {
        let body = format!(
            "{{ std::string __r; {}return __r; }}",
            seg_stmts(&arm.segs, &acc)
        );
        match &arm.cond {
            Some(c) => {
                let kw = if i == 0 { "if" } else { "else if" };
                code.push_str(&format!(
                    "{kw} (({}) != 0) {body} ",
                    emit_cond(c, "word", &cond_acc)
                ));
            }
            None => {
                if i == 0 {
                    code.push_str(&body);
                } else {
                    code.push_str(&format!("else {body} "));
                }
                saw_uncond = true;
                break;
            }
        }
    }
    if !saw_uncond {
        code.push_str(&format!("return {};", c_string(&inst.name)));
    }

    code
}

fn disasm_fn(isa: &Isa, m: &Model) -> String {
    let handle = handle_ty(isa);
    let acc_names = computed_accessor_names(isa);
    let mut s = String::new();

    if m.modal {
        let _ = writeln!(
            s,
            "static inline std::string disasm(unsigned combo, {handle} word) {{"
        );
    } else {
        let _ = writeln!(s, "static inline std::string disasm({handle} word) {{");
    }
    s.push_str("    char buf[64];\n    (void)buf;\n");

    if m.modal {
        s.push_str("    switch (classify(combo, word)) {\n");
    } else {
        s.push_str("    switch (classify(word)) {\n");
    }
    for &idx in &isa.instr_order() {
        let inst = &isa.instrs[idx];
        let _ = writeln!(s, "    case OP_{}: {{", cname(&inst.name));
        let _ = writeln!(s, "        {}", arms_block(&acc_names, inst));
        s.push_str("    }\n");
    }
    s.push_str("    default: return \"(invalid)\";\n    }\n}\n");

    s
}
